openedxstats/apps/sites/urls.py
from django.urls import path
from openedxstats.apps.sites import views

app_name = 'sites'
urlpatterns = [
    path('sites/all/', views.ListAllView.as_view(), name='sites_all_list'),
    path('sites/all/json', views.SiteView_JSON, name='sites_list_json'),
    path('sites/current/', views.ListView.as_view(), name='sites_list'),
    path('sites/map/', views.MapView.as_view(), name='sites_map'),
    path('sites/stats/', views.stats_view, name='sites_stats'),
    path('sites/add_site/', views.add_site, name='add_site'),
    path('sites/update_site/<int:pk>/', views.add_site, name='update_site'),
    path('sites/add_language/', views.add_language, name='add_language'),
    path('sites/add_geozone/', views.add_geozone, name='add_geozone'),
    path('sites/site_detail/<int:pk>/', views.SiteDetailView.as_view(), name='site_detail'),
    path('sites/delete_site/<int:pk>/', views.SiteDelete.as_view(), name='delete_site'),
    path('sites/ot_chart/', views.OTChartView.as_view(), name='ot_chart'),
    path('sites/site_discovery/', views.SiteDiscoveryListView.as_view(), name='site_discovery'),
    path('sites/csv/', views.sites_csv_view, name='sites_csv'),
    path('sites/bulk_update/', views.bulk_update),
    path('sites/bulk_create/', views.bulk_create),
]

openedxstats/urls.py
from django.urls import include, path, re_path
from django.contrib import admin
from django.http import HttpResponse
from django.contrib.auth import views as auth_views

from openedxstats.views import HomePageView

urlpatterns = [
    re_path(r'^robots\.txt$', lambda r: HttpResponse("User-Agent: *\nDisallow: /", mimetype="text/plain"), name="robots_file"),
    path('', HomePageView.as_view(), name='home'),
    re_path(r'^admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(
        redirect_authenticated_user=False, template_name='login.html', extra_context={'next': '/sites/current'}), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('', include('slackdata.urls')),
    path('', include('sites.urls', namespace="sites")),
]

openedxstats/apps/sites/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User
from django.contrib.postgres.forms import SimpleArrayField
from openedxstats.apps.sites.models import Site, Language, GeoZone
from datetimewidget.widgets import DateTimeWidget
from django.template.defaultfilters import mark_safe

default_url_errors = {
    'required': 'This field is required',
    'invalid': 'Enter a valid URL, i.e. https://example.com'
}

class SiteForm(forms.ModelForm):
    url = forms.URLField(max_length=1000, required=True, error_messages=default_url_errors)
    aliases = SimpleArrayField(forms.CharField(), required=False, delimiter='\n', widget=forms.Textarea)

    class Meta:
        model = Site
        exclude = ['active_end_date', 'github_fork', 'registered_user_count', 'active_learner_count', 'course_type',]
        # If the corresponding attribute in site form is uncommented above, these help messages won't show
        help_texts = {
            "language": "Select multiple languages with CMD+Click",
            "geography": "Select multiple geo-zones with CMD+Click",
            #'url': 'This text is not persistent on page, what gives!',
            #'last_checked': 'This text is persistent on the page, conflicts with error help text provided by bootstrap',
        }
        widgets = {
            'active_start_date': DateTimeWidget(attrs={'id': 'active_start_date'}, bootstrap_version=3),
        }


class LanguageForm(forms.ModelForm):

    class Meta:
        model = Language
        fields = ['language_name']
        labels = {
            'languange_name': _('Add Language'),
        }

class GeoZoneForm(forms.ModelForm):

    class Meta:
        model = GeoZone
        fields = ['geozone_name']
        labels = {
            'geozone_name': _('Add Geozone'),
        }

    def __init__(self, *args, **kwargs):
        # first call parent's constructor
        super(GeoZoneForm, self).__init__(*args, **kwargs)
        # there's a `fields` property now
        self.fields['geozone_name'].required = False



class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = '__all__'

openedxstats/apps/sites/views.py
import csv
from datetime import datetime, timedelta
import requests
import json
import re
from urllib import parse

import yaml

from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.urls import reverse, reverse_lazy

from django.contrib import messages
from django.core import serializers
from django.core.exceptions import ValidationError
from django.db.models import Count, Sum, Q
from django.views.decorators.csrf import csrf_exempt
from openedxstats.apps.sites.models import (
    Site, SiteLanguage, SiteGeoZone, Language, GeoZone, SiteSummarySnapshot,
    AccessLogAggregate, OverCount,
)
from openedxstats.apps.sites.forms import SiteForm, LanguageForm, GeoZoneForm

def bool_option(request, opt_name):
    return request.GET.get(opt_name, "f").lower()[0] in "ty1"

# Converts site data into JSON format for Ajax request
def SiteView_JSON(request):
    resp_data = {}

    if bool_option(request, "all"):
        sites = Site.objects.all()
    else:
        sites = Site.objects.exclude(active_end_date__isnull=False).filter(valid_sites_query())

    resp_data["sites"] = serializers.serialize("json", sites)

    if bool_option(request, "lang"):
        resp_data["language"] = serializers.serialize("json", SiteLanguage.objects.all())

    if bool_option(request, "geo"):
        resp_data["geo"] = serializers.serialize("json", SiteGeoZone.objects.all())

    if bool_option(request, "active_counts"):
        active_sites = Site.objects.exclude(active_end_date__isnull=False)
        active_sites_id_set = {site['id'] for site in active_sites.values('id')}
        country_list = [country['geo_zone'] for country in SiteGeoZone.objects.values('geo_zone').order_by('geo_zone').distinct()]
        country_site_count_dict = {country: 0 for country in country_list}
        all_geozone = SiteGeoZone.objects.values('site_id', 'geo_zone')
        for loc in all_geozone:
            site_id = loc['site_id']
            geo_zone = loc['geo_zone']
            if site_id in active_sites_id_set and active_sites.get(id=site_id).course_count != 0:
                country_site_count_dict[geo_zone] += 1
        resp_data["activeSitesCount"] = country_site_count_dict

    return JsonResponse(resp_data)

class ListSomeView(generic.TemplateView):
    template_name = 'sites/sites_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['all'] = self.all
        return context

class ListAllView(ListSomeView):
    all = True

class ListView(ListSomeView):
    all = False


class SiteDetailView(generic.DetailView):
    model = Site
    template_name = 'sites/site_detail.html'
    context_object_name = 'site'


class SiteDelete(generic.DeleteView):
    model = Site
    template_name = 'sites/delete_site.html'
    success_url = reverse_lazy('sites:sites_list')

class MapView(generic.ListView):
    model = Site
    template_name = 'sites/sites_map.html'
    context_object_name = 'sites_map'

def stats_view(request):
    active_sites = Site.objects.exclude(active_end_date__isnull=False).filter(valid_sites_query()).aggregate(sites=Count('*'), courses=Sum('course_count'))
    over_count = OverCount.objects.all().last().course_count
    valid_course_count = active_sites['courses'] - over_count
    language_count = Language.objects.all().count()
    geozones_count = GeoZone.objects.all().count()
    stats_dict = {
        'sites': active_sites['sites'],
        'courses': valid_course_count,
        'languages': language_count,
        'countries': geozones_count
    }
    return render(request, 'sites/sites_stats.html', context=stats_dict)

def json_response(text=None, data=None, **response_kwargs):
    """Create a JSON response"""
    if text is None:
        text = json.dumps(data)
    return HttpResponse(text, content_type='application/json', **response_kwargs)


def get_netloc(url):
    """
    Return domain of url if parseable
    """
    if '//' in url:
        netloc = parse.urlparse(url).netloc
    else:
        netloc = url
    return netloc.rstrip(".")


class SiteDiscoveryListView(generic.TemplateView):
    template_name = 'sites/site_discovery.html'

    def discover_domains(self, start_date, end_date):
        """
        Grab aggregate referrer logs from database (that were generated by referrer log script), and compare to sites
        on record, returning domain names that are not in sites list.
        """

        # This is hundreds of thousands of records, and will grow considerably unless the database is regularly cleaned
        # If loading the discovery page begins to lag considerably, a default query other than all data available
        # (e.g. logs from the last day only) should be considered to shorten initial load time
        sites = Site.objects.all()
        known_domains = set()
        known_domains.update(get_netloc(site.url) for site in sites)
        known_domains.update(get_netloc(url) for site in sites for url in site.aliases)

        # Filter out all logs with domains that are: aws owned, edx owned, blank, an ip address, and/or have a custom port
        # Then aggregate based on domain and access date
        aggregate_logs_by_day = AccessLogAggregate.objects.filter(
            ~Q(domain__endswith='.amazonaws.com') & ~Q(domain__endswith='.edx.org') & ~Q(domain='') &
             ~Q(domain__regex=r'^[0-9]+(?:\.[0-9]+){3}$') & ~Q(domain__regex=r':[0-9]+')
        ).values(
            'access_date',
            'domain'
        ).annotate(
            count=Sum('access_count')
        )

        # If date range specified, filter dates accordingly
        if start_date != '' and end_date != '':
            aggregate_logs_by_day = aggregate_logs_by_day.filter(access_date__range=[start_date, end_date])

        # Filter out objects that don't fall within date range and then combine into one record
        aggregate_logs_by_day = aggregate_logs_by_day.values('domain').annotate(count=Sum('access_count'))

        # Add to final query set if domain isn't already on record
        chaff = ['www', 'studio', 'staging', 'preview', 'stage', 'cms']
        new_domains = []
        for log in aggregate_logs_by_day:
            netloc = get_netloc(log['domain'])
            short_netloc = ".".join(part for part in netloc.split(".") if part not in chaff)
            if netloc not in known_domains and short_netloc not in known_domains:
                new_domains.append(log)

        return new_domains

    def post(self, request, *args, **kwargs):
        new_domains = self.discover_domains(request.POST['start_date'], request.POST['end_date'])
        return json_response(data=new_domains)


class OTChartView(generic.list.MultipleObjectTemplateResponseMixin, generic.list.BaseListView):
    model = SiteSummarySnapshot
    template_name = 'sites/ot_chart.html'
    context_object_name = 'snapshot_list'

    def daterange(self, start_date, end_date):
        """
        This function is used to generate a date range, with one day increments. Notice the +1 adjustment on day, and -1
        adjustment on seconds. This is used to ensure each day is actually a datetime of the last second of that day, to
        allow for correct aggregation when querying the database with these dates.
        """
        for n in range(int((end_date - start_date).days)):
            yield start_date + timedelta(days=n+1, seconds=-1)

    def generate_summary_data(self, start_datetime):
        """
        Generate site total and course totals by day since ending of site summary snapshots were recorded
        """
        daily_summary_obj_list = []
        # Generate a summary of total sites and courses active for each day in a range of dates
        for day in self.daterange(start_datetime, datetime.now() + timedelta(days=1)):
            # Query to get all site versions that are active within the specified date period
            # We only count public sites with > 0 courses, and count all private sites
            date_select = (
                Q(active_start_date__lte=day) &
                (Q(active_end_date__gte=day) | Q(active_end_date=None))
            )

            day_stats = Site.objects.filter(
                valid_sites_query() &
                date_select
            ).aggregate(sites=Count('*'), courses=Sum('course_count'))
            try:
                over_count = OverCount.objects.get(date_select).course_count
            except OverCount.DoesNotExist:
                over_count = 0
            # Generate summary object for day

            daily_courses_count = day_stats['courses']
            if daily_courses_count is None:
                daily_courses_count = 0

            print(f"Making a new summary for {day}")
            daily_summary_obj = SiteSummarySnapshot(
                timestamp=day,
                num_sites=day_stats['sites'],
                num_courses=daily_courses_count - over_count,
                notes="Auto-generated day summary"
            )
            daily_summary_obj.save()
            daily_summary_obj_list.append(daily_summary_obj)

        return daily_summary_obj_list

    def post(self, request, *args, **kwargs):
        old_ot_data = []
        new_ot_data = []
        if SiteSummarySnapshot.objects.count() > 0 or Site.objects.count() > 0:
            # Get old data (pre-historical tracking implementation)
            old_ot_data = list(SiteSummarySnapshot.objects.all())
            # Gets oldest site summary snapshot from db, after this point we will generate statistics from site versions
            start_datetime = SiteSummarySnapshot.objects.all().order_by('-timestamp').first().timestamp + timedelta(days=1)
            # Generate new data
            new_ot_data = self.generate_summary_data(start_datetime)

        serialized_data = serializers.serialize('json', old_ot_data+new_ot_data)

openedxstats/apps/sites/templates/sites/add_geozone.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load static %}
{% block bootstrap3_extra_head %}
    <script>
        $(document).ready(function () {
            var url = window.location;
            $('ul.nav.navbar-nav li a[href="' + url.pathname + '"]').parent().addClass('active');
        });
    </script>
    <link rel="shortcut icon" href="{%  static 'sites/favicon.ico' %}">
    {{ form.media }}
{% endblock %}


{% block title %} Add GeoZone {% endblock %}
{% block content %}
    <!-- Navbar -->
    {% include "navbar.html" %}
    <!-- Content -->
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                <!-- Insert form here -->
                <form action="{% url 'sites:add_geozone'%}" method="post" class="form">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <input type="submit" class="btn btn-primary" value="Submit" />
                </form>
            </div>
            <div class="col-md-6">
                <p>
                    <!--Something will be here soon maybe.-->
                </p>
            </div>
        </div>
    <br />
    </div>
{% endblock %}

openedxstats/apps/sites/templates/sites/add_language.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load static %}
{% block bootstrap3_extra_head %}
    <script>
        $(document).ready(function () {
            var url = window.location;
            $('ul.nav.navbar-nav li a[href="' + url.pathname + '"]').parent().addClass('active');
        });
    </script>
    <link rel="shortcut icon" href="{%  static 'sites/favicon.ico' %}">
    {{ form.media }}
{% endblock %}


{% block title %} Add Language {% endblock %}
{% block content %}
    <!-- Navbar -->
    {% include "navbar.html" %}
    <!-- Content -->
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                <!-- Insert form here -->
                <form action="{% url 'sites:add_language'%}" method="post" class="form">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <input type="submit" class="btn btn-primary" value="Submit" />
                </form>
            </div>
            <div class="col-md-6">
                <p>
                    <!--Something will be here soon maybe.-->
                </p>
            </div>
        </div>
    <br />
    </div>

{% endblock %}

openedxstats/apps/sites/templates/sites/delete_site.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load static %}
{% block bootstrap3_extra_head %}
    <script>
        $(document).ready(function () {
            var url = window.location;
            $('ul.nav.navbar-nav li a[href="' + url.pathname + '"]').parent().addClass('active');
        });
    </script>
    <link rel="shortcut icon" href="{%  static 'sites/favicon.ico' %}">
    {{ form.media }}
{% endblock %}

{% block title %}{% endblock %}
{% block content %}
    <!-- Navbar -->
    {% include "navbar.html" %}
    <!-- Content -->
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                <!-- Insert form here -->
                <form action="{% url "sites:delete_site" pk=site.id %}" method="post" class="form">
                    {% csrf_token %}
                    <p>Are you sure you want to delete "{{ site.url }}"?</p>
                    <input type="submit" class="btn btn-default btn-danger" value="Delete"/>
                    <a href="{% url "sites:sites_list" %}">
                        <button type="button" class="btn btn-default" value="Cancel">Cancel</button>
                    </a>
                </form>
            </div>
        </div>
        <br/>
    </div>
{% endblock %}

openedxstats/apps/sites/templates/sites/sites_list.html
{% extends "base.html" %}
{% load static %}
{% block title %} Open edX Sites List {% endblock %}
{% block bootstrap3_extra_head %}
    <link rel="shortcut icon" href="{%  static 'sites/favicon.ico' %}">
    <style type="text/css">
        .action-button-cell {
            padding-left: 2px;
            padding-right: 2px;
        }
        .extra-padding-10 {
            padding-top: 5px;
            padding-bottom: 15px;
        }
    </style>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/u/bs/dt-1.10.12/datatables.min.css"/>
    <script type="text/javascript" src="https://cdn.datatables.net/u/bs/dt-1.10.12/datatables.min.js"></script>
    <script>
        $(document).ready(function () {
            // Nav active class selection
            var url = window.location;
            $('ul.nav.navbar-nav li a[href="' + url.pathname + '"]').parent().addClass('active');
            // Tooltips
            $('[data-toggle="tooltip"]').tooltip();
            // Table sorting

            //    isCurrentVersion
            //    Determine rendering of green check box based on whether site is of the current version based on the sites active end date for each row
            isCurrentVersion = activeEndDate => activeEndDate ? '' : '<span class="glyphicon glyphicon-ok" aria-hidden="true" style="color: green; font-size: 30px;"></span>'

            //    renderActionButtons
            //    Accepts arguments of the site ID and the website's active end date to determine which buttons to render inside the row under column 'Actions'
            //    At minimum will render the button for 'Detail' and 'Delete', 'Update' will be rendered if website is still active.
            function renderActionButtons(siteId, activeEndDate) {
                const detail_site = `<td class="action-button-cell"><a href="/sites/site_detail/${siteId}"><button type="button" class="btn btn-primary" aria-label="Detail" data-toggle="tooltip" data-placement="bottom" title="Detail"><span class="glyphicon glyphicon-list" aria-hidden="true"></span></button></a></td>`
                const update_site = `<td class="action-button-cell"><a href="/sites/update_site/${siteId}"><button type="button" class="btn btn-primary" aria-label="Edit" data-toggle="tooltip" data-placement="bottom" title="Edit"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></button></a></td>`
                const delete_site = `<td class="action-button-cell"><a href="/sites/delete_site/${siteId}"><button type="button" class="btn btn-danger" aria-label="Delete" data-toggle="tooltip" data-placement="bottom" title="Delete"><span class="glyphicon glyphicon-trash"></span></button></a></td>`
                return `<td style="width: 1%; vertical-align: middle;"><table><tr>${detail_site + (!activeEndDate ? update_site : '') + delete_site}</tr></table></td>`
            }

            //  renderUrlString
            //  Converts site URL into HTML link tag
            renderUrlString = url => `<a href="${url}">${url}</a>`

            //    Datatables configuration
            //    Data is retrieved the API end point served from the view 'sites_list_json' (see views.py)
            var sitesTable = $('#sites').DataTable({
                "processing": true,
                "ajax":{
                    // Communicating to API endpoint serving JSON data from database
                    "url":"{% url 'sites:sites_list_json' %}{% if all %}?all=1&lang=1&geo=1{% endif %}",
                    "dataSrc": function(json) {                // Formatting data to be compatible with DataTables
                        const data = JSON.parse(json.sites);

                        {% if all %}
                        const siteGeolocation = {};
                        const geoData = JSON.parse(json.geo);
                        geoData.forEach(function(geoLoc) {
                            siteGeolocation[geoLoc.fields.site] = geoLoc.fields.geo_zone;
                        })

                        const siteLanguage = {}
                        const languageData = JSON.parse(json.language);
                        languageData.forEach(function(lang) {
                            siteLanguage[lang.fields.site] = lang.fields.language;
                        })
                        {% endif %}

                        Object.keys(data).forEach(function(siteID) {
                            const site = data[siteID];
                            site.fields['actionButtons'] = renderActionButtons(site.pk, site.fields.active_end_date);
                            site.fields['urlString'] = renderUrlString(site.fields.url);
                            {% if all %}
                            site.fields['isCurrentVersion'] = isCurrentVersion(site.fields.active_end_date);
                            const sitePK = data[siteID].pk
                            site.fields['geolocation'] = siteGeolocation[sitePK] ? siteGeolocation[sitePK] : '';
                            site.fields['language'] = siteLanguage[sitePK] ? siteLanguage[sitePK] : '';
                            {% endif %}
                        });
                        return data;
                    }},
                "columns": [                                    // Data for each row item from JSON
                     { "data": "fields.site_type" },
                     { "data": "fields.name" },
                     { "data": "fields.urlString" },
                     { "data": "fields.course_count" },
                     { "data": "fields.active_start_date" },
                    {% if all %}
                     { "data": "fields.active_end_date" },
                     { "data": "fields.is_gone" },
                     { "data": "fields.isCurrentVersion" },
                     { "data": "fields.geolocation", "visible": false },
                     { "data": "fields.notes", "visible": false },
                     { "data": "fields.language", "visible": false },
                    {% endif %}
                     { "data": "fields.actionButtons" }
                ]
            });

            // Filtering
            $.fn.dataTable.ext.search.push(function (settings, data, dataIndex) {
                {% if all %}
                var goodDate, goodCourses, goodSite;

                var latestOnly = $("#latestOnly").prop("checked") && !$('#dateInput').val();
                if (latestOnly) {
                    goodDate = isNaN(Date.parse(data[5]));
                }
                else {
                    goodDate = Date.parse(data[4]) <= Date.parse($('#dateInput').val() || data[4])
                        && (Date.parse($('#dateInput').val() || data[5]) <= Date.parse(data[5])
                            || isNaN(Date.parse(data[5])));
                }

                var hideZeros = $("#hideZeros").prop("checked");
                if (hideZeros) {
                    goodCourses = data[3] !== "0";
                }
                else {
                    goodCourses = true;
                }

                var hideGone = $("#hideGone").prop("checked");
                if (hideGone) {
                    goodSite = data[6] === "false";
                }
                else {
                    goodSite = true;
                }

                return goodDate && goodCourses && goodSite;
                {% else %}
                return true;
                {% endif %}
            });
            $('#dateSearchButton').on('click', sitesTable.draw);
            $('#latestOnly').on('click', sitesTable.draw);
            $('#hideZeros').on('click', sitesTable.draw);
            $('#hideGone').on('click', sitesTable.draw);
            $('#dateInput').keyup(function (e) {
                if (e.keyCode == 13) {
                    sitesTable.draw()
                }
            });
        });
    </script>
{% endblock %}
{% block content %}
    <!-- Navbar -->
    {% include "navbar.html" %}
    <!-- Content -->
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                {% if all %}
                <p>
                    Use the date search bar to enter a datetime <em>(YYYY-MM-DD HH:MM)</em> you wish to see a list of
                    sites active at that time for. For instance, if you enter <em>2016-04-03 05:37</em>, the version of
                    each site that was 'current' at that time will be displayed. You may also use <em>YYYY-MM-DD</em>
                    format for less precise searching. If you enter any date in the future, you will be returned all of
                    the most current site versions. If you want to see all versions of a single site, try entering
                    its name (or better yet, URL) into the generic search bar on the right. Use the links above to
                    perform other actions like adding a new site or site version, language, or geozone.
                </p>
                {% else %}
                <p>Historical, language, and geographic data is on the <a href="/sites/all">/sites/all</a> page.</p>
                {% endif %}
                <p style="font-weight: bold;">
                    Comprehensive documentation and source code can be found <a target="_blank"
                        href="https://github.com/openedx/openedxstats">here</a>.
                </p>
            </div>
        </div>
        {% if all %}
        <div class="row extra-padding-10">
            <div class="col-md-4">
                <div class="input-group">
                    <input id="dateInput" type="text" class="form-control" placeholder="YYYY-MM-DD HH:MM">
                    <span class="input-group-btn">
                        <button id="dateSearchButton" class="btn btn-primary" type="button" aria-label="Search Date">
                            Search Date
                        </button>
                    </span>
                </div>
            </div>
            <div class="col-md-2">
                <input id="latestOnly" type="checkbox" value="Latest Only" checked="checked"> Latest Only
            </div>
            <div class="col-md-2">
                <input id="hideZeros" type="checkbox" value="Hide Zeros" checked="checked"> Hide Zeros
            </div>
            <div class="col-md-2">
                <input id="hideGone" type="checkbox" value="Hide Gone" checked="checked"> Hide Gone
            </div>
        </div>
        {% endif %}
        <table id="sites" class="table table-bordered table-responsive table-sm">
            <thead>
            <tr>
                <th>Site Type</th>
                <th>Name</th>
                <th>Url</th>
                <th>Course Count</th>
                <th>Active Version Start</th>
                {% if all %}
                <th>Active Version End</th>
                <th>Is gone?</th>
                <th>Current Version?</th>
                <th>Geolocation</th>
                <th>Notes</th>
                <th>Language</th>
                {% endif %}
                <th>Actions</th>
            </tr>
            </thead>
            <tfoot>
            <tr>
                <th>Site Type</th>
                <th>Name</th>
                <th>Url</th>
                <th>Course Count</th>
                <th>Active Version Start</th>
                {% if all %}
                <th>Active Version End</th>
                <th>Is gone?</th>
                <th>Current Version?</th>
                <th>Geolocation</th>
                <th>Notes</th>
                <th>Language</th>
                {% endif %}
                <th>Actions</th>
            </tr>
            </tfoot>
        </table>
    </div>
{% endblock %}

openedxstats/apps/sites/templates/sites/update_site.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load static %}
{% block bootstrap3_extra_head %}
    <link rel="shortcut icon" href="{%  static 'sites/favicon.ico' %}">
    {{ form.media }}
{% endblock %}


{% block title %} Update Site {% endblock %}
{% block content %}
    <!-- Navbar -->
    {% include "navbar.html" %}
    <!-- Content -->
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                <!-- Insert form here -->
                <form action="{% url 'sites:update_site' pk=site.id %}" method="post" class="form">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <input type="submit" class="btn btn-primary" value="Update"/>
                    <a href="{% url "sites:sites_list" %}">
                        <button type="button" class="btn btn-default" value="Cancel">Cancel</button>
                    </a>
                </form>
            </div>
        </div>
        <br/>
    </div>
{% endblock %}